name: Build and Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Build Hugo site
        run: hugo --minify

      - name: Deploy to Cloudflare Pages
        uses: robertying/deploy-to-cloudflare-pages@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          project: me
          buildDir: public
